// <auto-generated />
using CSCI3110CRUDManyToMany.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSCI3110CRUDManyToMany.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("CSCI3110CRUDManyToMany.Models.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("CreditHours")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("CSCI3110CRUDManyToMany.Models.Entities.Internship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentENumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StudentENumber")
                        .IsUnique();

                    b.ToTable("Internships");
                });

            modelBuilder.Entity("CSCI3110CRUDManyToMany.Models.Entities.Student", b =>
                {
                    b.Property<string>("ENumber")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("ENumber");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("CSCI3110CRUDManyToMany.Models.Entities.StudentCourseGrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LetterGrade")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentENumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentENumber");

                    b.ToTable("StudentCourseGrades");
                });

            modelBuilder.Entity("CSCI3110CRUDManyToMany.Models.Entities.Internship", b =>
                {
                    b.HasOne("CSCI3110CRUDManyToMany.Models.Entities.Student", "Student")
                        .WithOne("Internship")
                        .HasForeignKey("CSCI3110CRUDManyToMany.Models.Entities.Internship", "StudentENumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CSCI3110CRUDManyToMany.Models.Entities.StudentCourseGrade", b =>
                {
                    b.HasOne("CSCI3110CRUDManyToMany.Models.Entities.Course", "Course")
                        .WithMany("StudentGrades")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSCI3110CRUDManyToMany.Models.Entities.Student", "Student")
                        .WithMany("CourseGrades")
                        .HasForeignKey("StudentENumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CSCI3110CRUDManyToMany.Models.Entities.Course", b =>
                {
                    b.Navigation("StudentGrades");
                });

            modelBuilder.Entity("CSCI3110CRUDManyToMany.Models.Entities.Student", b =>
                {
                    b.Navigation("CourseGrades");

                    b.Navigation("Internship");
                });
#pragma warning restore 612, 618
        }
    }
}
